# Generated by Django 5.2.3 on 2025-06-30 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do administrador')),
                ('login', models.CharField(max_length=50, unique=True, verbose_name='Login')),
                ('senha', models.CharField(max_length=128, verbose_name='Senha')),
                ('permissoes', models.CharField(choices=[('Total', 'Acesso total'), ('Parcial', 'Acesso parcial'), ('Leitura', 'Somente leitura')], max_length=20, verbose_name='Permissões')),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
            },
        ),
        migrations.CreateModel(
            name='Adotado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do adotado')),
                ('idade', models.IntegerField(verbose_name='Idade')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo')),
                ('data_nasc', models.DateField(verbose_name='Data de nascimento')),
                ('situacao', models.CharField(max_length=100, verbose_name='Situação atual')),
                ('necessidades_especiais', models.BooleanField(default=False, verbose_name='Possui necessidades especiais')),
            ],
            options={
                'verbose_name': 'Adotado',
                'verbose_name_plural': 'Adotados',
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
            },
        ),
        migrations.CreateModel(
            name='Informativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('categoria', models.CharField(choices=[('Dúvidas frequentes', 'Dúvidas frequentes'), ('Documentos necessários', 'Documentos necessários'), ('Etapas do processo', 'Etapas do processo'), ('Direitos e deveres', 'Direitos e deveres'), ('Outros', 'Outros')], max_length=50, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Informativo',
                'verbose_name_plural': 'Informativos',
            },
        ),
        migrations.CreateModel(
            name='Adotante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do adotante')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('data_nasc', models.DateField(verbose_name='Data de nascimento')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('preferencia_idade', models.CharField(max_length=50, verbose_name='Preferência de idade')),
                ('aceita_grupo_irmaos', models.BooleanField(default=False, verbose_name='Aceita grupo de irmãos')),
                ('aceita_necessidades_especiais', models.BooleanField(default=False, verbose_name='Aceita necessidades especiais')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidade', verbose_name='Cidade do adotante')),
            ],
            options={
                'verbose_name': 'Adotante',
                'verbose_name_plural': 'Adotantes',
            },
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da instituição')),
                ('tipo', models.CharField(choices=[('Abrigamento', 'Abrigamento'), ('Juizado', 'Juizado'), ('ONG', 'ONG'), ('Outro', 'Outro')], max_length=20, verbose_name='Tipo de instituição')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidade', verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Instituição',
                'verbose_name_plural': 'Instituições',
            },
        ),
        migrations.CreateModel(
            name='ProcessoAdocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Em análise', 'Em análise'), ('Aprovado', 'Aprovado'), ('Rejeitado', 'Rejeitado'), ('Concluído', 'Concluído'), ('Cancelado', 'Cancelado')], max_length=20, verbose_name='Status do processo')),
                ('data_inicio', models.DateField(verbose_name='Data de início')),
                ('data_atualizacao', models.DateField(verbose_name='Última atualização')),
                ('adotado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.adotado', verbose_name='Adotado')),
                ('adotante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.adotante', verbose_name='Adotante')),
            ],
            options={
                'verbose_name': 'Processo de Adoção',
                'verbose_name_plural': 'Processos de Adoção',
            },
        ),
        migrations.CreateModel(
            name='Compatibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grau_de_compatibilidade', models.IntegerField(verbose_name='Grau de compatibilidade (%)')),
                ('adotado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.adotado', verbose_name='Adotado')),
                ('adotante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.adotante', verbose_name='Adotante')),
            ],
            options={
                'verbose_name': 'Compatibilidade',
                'verbose_name_plural': 'Compatibilidades',
                'unique_together': {('adotante', 'adotado')},
            },
        ),
    ]
