# Generated by Django 5.2.3 on 2025-07-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adotado',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_adotados/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='adotado',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, verbose_name='Sexo'),
        ),
    ]
